spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: 
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties-hibernate-dialect: org.hibernate.dialect.MySQL8Dialect
